name: UniCourseHub
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: buildSpringBoorProjects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setupJdk21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: buildApllication
        run: |
          mvn clean 
          mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: setVersionToCurrentDate
        id: set-version
        run: |
          DATE_VERSION=$(DATE+'%'Y%m%d-%H%M)
          echo "DATE_VERSION=$DATE_VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/uniCourseHub:${{ env.DATE_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/uniCourseHub:${{ env.DATE_VERSION }}